# Generated by Django 4.1.7 on 2023-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
