# Generated by Django 4.1.7 on 2023-03-13 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0002_alter_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='station',
            name='type',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
