# Generated by Django 4.1.7 on 2023-03-19 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0004_station_origin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='latitude',
            new_name='lat',
        ),
        migrations.RenameField(
            model_name='station',
            old_name='longitude',
            new_name='long',
        ),
    ]
