# Generated by Django 4.1.7 on 2023-04-03 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0005_rename_latitude_station_lat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='category',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='station',
            name='dhmos',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
