# Generated by Django 4.1.7 on 2023-04-19 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0006_station_category_station_dhmos'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='mean',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
