# Generated by Django 4.1.7 on 2023-04-21 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0008_dhmos_station_chargers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='station',
            old_name='category',
            new_name='chargers_num',
        ),
        migrations.RemoveField(
            model_name='station',
            name='chargers',
        ),
        migrations.AlterField(
            model_name='station',
            name='dhmos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charging_stations.dhmos'),
        ),
    ]
