# Generated by Django 4.1.7 on 2023-04-21 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0009_rename_category_station_chargers_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dhmos',
            name='chargers',
        ),
        migrations.AddField(
            model_name='dhmos',
            name='category_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
