# Generated by Django 4.1.7 on 2023-04-21 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0011_alter_station_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together={('lat', 'long')},
        ),
    ]
