# Generated by Django 4.1.7 on 2023-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0012_alter_station_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
