# Generated by Django 4.1.7 on 2023-04-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0013_alter_station_address'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='station',
            unique_together=set(),
        ),
    ]
