# Generated by Django 4.1.7 on 2023-05-09 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0014_alter_station_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='mean_updating',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
