# Generated by Django 4.1.7 on 2023-05-18 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charging_stations', '0017_profile_last_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
