services:  

  web:
    build: ../backend  
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ../backend:/usr/src/backend
    env_file:
      - ./.env.dev
    depends_on:
    - db

  db: 
    image: postgres:15
    volumes:
      - .data/postgres_data:/var/lib/postgresql/data/
    command: -p 5000
    ports:
      - '5000:5000'
    expose:
      - '5000'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pitarda12
      - POSTGRES_DB=ChargingStations    

  frontend:
    build: 
      context: ../charging-stations
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ../charging-stations:/frontend
      
volumes:
  postgres_data:
